FROM public.ecr.aws/lambda/python:3.9

# Copy requirements and install
COPY requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy handler
COPY dev_handler.py ${LAMBDA_TASK_ROOT}/

CMD ["dev_handler.lambda_handler"]
