name: Mini E2E + Health

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: python -m pip install -r lambda/dev_requirements.txt

      - name: Run Phase 2 verification suite
        run: bash scripts/phase2_verification.sh

      - name: Publish verification artifact
        if: always()
        run: |
          mkdir -p artifacts
          if [ -f .out/verification.json ]; then
            cp .out/verification.json artifacts/verification.json
          else
            echo '{}' > artifacts/verification.json
          fi

      - name: Upload verification artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: verification
          path: artifacts/verification.json

  k6:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run k6 smoke test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: k6/smoke.js
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          BEARER: ${{ secrets.BEARER }}
          USER: ${{ secrets.TEST_USER }}
